version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: deploy/prod/Dockerfile
    container_name: laravel_app_prod
    volumes:
      - ./:/var/www
    depends_on:
      - db
    entrypoint: ["/usr/local/bin/entrypoint"]
    command: ["php-fpm"]
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel_prod
      - DB_USERNAME=produser
      - DB_PASSWORD=prodpassword

  nginx:
    image: nginx:stable
    container_name: nginx_server_prod
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ../../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: pgsql_db_prod
    environment:
      POSTGRES_DB: laravel_prod
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
