version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/prod/Dockerfile
    container_name: laravel_app_prod
    volumes:
      - ../..:/var/www
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    entrypoint: ["/usr/local/bin/entrypoint"]
    command: ["php-fpm"]

  nginx:
    image: nginx:stable
    container_name: nginx_server_prod
    ports:
      - 8001:80  # <- Aqui está a mudança
    volumes:
      - ../..:/var/www:ro
      - ../../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: pgsql_db_prod
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

volumes:
  pgdata_prod:
